### PR TITLE
Condense program logic and flow 

### PR DESCRIPTION
**Pull request by atrievel**
I would like to resolve issue #1. Here is a summary of the work I completed:

##### Checklist
- [X]  create 'main' file for users to run with specified options
- [X]  reduce duplicate code in each .py file (logo, menu options, etc.)
- [X]  re-run tests on provided image
- [X] updated documentation with my changes and spelling mistakes

### Affected core subsystem(s)
The core image processing functionality is unaffected by these changes. 

### Description of change
Users can now run the application by passing arguments to a single 'main' file: `ImageRemakeCLI.py`. The basic logic of the image processing functions written by @TomasRoj  does not change.

### CODE REVIEW

**Comment by TomasRoj** [comment]
Thank you VERY much for your contribution. I didnt expect that anyone will find it and make some changes. I would be proud to merge it. Do you tested it? Are you sure everything is working perfectly? I am not availibe on pc now unfortuntatly.

**Comment by atrievel** [comment]
@TomasRoj yes I tested it with all the functions you wrote (blur, sharpen, rotate, resize) and it all works like it did before my changes. I really didn't have to change to core functionality that you wrote at all since I was basically just adding a 'menu'. Glad to see it met your requirements though! 😄

**Comment by TomasRoj** [comment]
Great! I am always trying to make 100% sure that everthing works perfectyl before merging. I failed at this step multiple times in the past. I am merging this pull request. BTW: do you have a minute to chat a little bit? Do you have discord or something?

**Comment by atrievel** [comment]
No worries! You can always revert the changes back to a stable branch if my changes don't meet your requirements. My discord is AlecT58

**Comment by TomasRoj** [comment]
Thanks!

**Pull request merged**
